# Generated by Django 6.0 on 2026-01-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TripType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("trip_type_name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="VehiculeType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vehicule_type_name", models.CharField(max_length=120)),
                ("vehicule_max_seats", models.IntegerField(default=4, null=True)),
                ("vehicule_price_distance", models.FloatField(default=1.8, null=True)),
                ("vehicule_price_hour", models.FloatField(default=45.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("address_start", models.CharField(null=True)),
                ("address_end", models.CharField(null=True)),
                ("date_start", models.DateField(null=True)),
                ("time_start", models.TimeField(null=True)),
                ("nb_passengers", models.IntegerField(default=1, null=True)),
                ("nb_luggages", models.IntegerField(default=0, null=True)),
                ("last_name", models.CharField(null=True)),
                ("first_name", models.CharField(null=True)),
                ("phone", models.CharField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("note", models.CharField(null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("duration", models.IntegerField(null=True)),
                ("distance", models.FloatField(null=True)),
                ("date_reservation", models.DateField(auto_now_add=True, null=True)),
                (
                    "trip_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reservations.triptype",
                    ),
                ),
                (
                    "car_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reservations.vehiculetype",
                    ),
                ),
            ],
        ),
    ]
