# Generated by Django 6.0.1 on 2026-02-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("address_start", models.CharField(null=True)),
                ("address_end", models.CharField(null=True)),
                ("date_start", models.DateField(null=True)),
                ("time_start", models.TimeField(null=True)),
                (
                    "car_type",
                    models.CharField(
                        choices=[("car", "Voiture"), ("van", "Van")], default="car"
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[("simple", "Simple"), ("hourly", "Hourly")],
                        default="simple",
                    ),
                ),
                ("nb_passengers", models.IntegerField(default=1, null=True)),
                ("nb_luggages", models.IntegerField(default=0, null=True)),
                ("last_name", models.CharField(null=True)),
                ("first_name", models.CharField(null=True)),
                ("phone", models.CharField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("note", models.CharField(null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("duration", models.IntegerField(null=True)),
                ("distance", models.FloatField(null=True)),
                ("date_reservation", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
