# Generated by Django 6.0 on 2025-12-13 15:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TripType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_type_name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="VehiculeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicule_type_name", models.CharField(max_length=120)),
                ("vehicule_max_seats", models.IntegerField(null=True)),
                ("vehicule_price_distance", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_start", models.CharField(null=True)),
                ("address_end", models.CharField(null=True)),
                ("date_start", models.DateField(null=True)),
                ("time_start", models.TimeField(null=True)),
                ("nb_passengers", models.IntegerField(null=True)),
                ("nb_luggages", models.IntegerField(null=True)),
                ("last_name", models.CharField(null=True)),
                ("first_name", models.CharField(null=True)),
                ("phone", models.CharField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("note", models.CharField(null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("duration", models.IntegerField(null=True)),
                ("distance", models.FloatField(null=True)),
                ("date_reservation", models.DateField(auto_now_add=True, null=True)),
                ("public_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "trip_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reservations.triptype",
                    ),
                ),
                (
                    "car_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reservations.vehiculetype",
                    ),
                ),
            ],
        ),
    ]
