# Generated by Django 6.0.1 on 2026-02-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='trip_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('hourly', 'Mise à disposition')], default='simple'),
        ),
    ]
