# Generated by Django 5.2.8 on 2025-12-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="address_start",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="address_stop",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="car_type",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="date_reservation",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="date_start",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="distance",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="first_name",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="last_name",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="nb_luggages",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="nb_passengers",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="note",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="phone",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="price",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="time_start",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="trip_type",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
