# Generated by Django 6.0 on 2025-12-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="nb_luggages",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="nb_passengers",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
