# Generated by Django 6.0 on 2025-12-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
